config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  devise_for :users
  root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  resources :orders
  resources :line_items
  resources :categories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="glyphicon glyphicon-menu-hamburger"></span>
      </button>
      <%= link_to "TTS", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Items",  root_path %></li>
        <!--<li><%= link_to "Items By Brand", branding_path %></li>-->
        <!--<li><%= link_to "Items By Category", categorical_path %></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @categories.each do |category|%> 
              <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @brands.each do |brand|%> 
              <li><%= link_to brand, branding_path(brand: brand) %></li>
            <% end %>
            <li><% link_to "All", root_path %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to view_order_path, class: "btn btn-primary navbar-btn" do %>
          <span class="glyphicon glyphicon-shopping-cart"></span> View Cart
        <% end %>
      </li>
      <% if current_user != nil %>
        <li>
          <%= link_to edit_user_registration_path, class: "btn btn-default navbar-btn" do %>
            <span class="glyphicon glyphicon-user"></span> Edit Profile
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, class: "btn btn-danger", method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Sign Out
          <% end %>
        </li>
      <% else %>
        <li><%= link_to new_user_registration_path, class: "btn btn-default navbar-btn" do %>
          <span class="glyphicon glyphicon-user"></span> Register
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, class: "btn btn-primary navbar-btn" do %>
            <span class="glyphicon glyphicon-log-in"></span> Sign In
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreFront</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>